name: sanity_deploy

on:
  push:
    branches:
      - main  # Adjust the branch as needed
  repository_dispatch:
    types:
      - sanity_publish


jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
     # Step 1: Установка Node.js версии 18
      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Указываем версию Node.js

      # Step 2: Checkout репозитория
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 3: Установка зависимостей и сборка
      - name: Install Dependencies and Build
        run: |
          npm install
          npm run build  # Сборка проекта
          
      # Step 4: Deploy files with rsync
      - name: Deploy with Rsync
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr --delete
          path: .
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_key: ${{ secrets.REMOTE_KEY }}
          remote_path: ${{ secrets.REMOTE_PATH }}  

       # Step 5: Выполнение дополнительных команд на сервере
      - name: Run Commands on Remote Server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_KEY }}
          script: |
            cd /home/cyclone/fireon.com.ua/admin
            ls -la  # Просматриваем файлы, чтобы убедиться в загрузке
            echo "Deployment complete!"
            
      # Step 4: Trigger action for another repository          
      - name: Trigger Workflow in Another Repository
        run: |
          # Set the required variables
          repo_owner="MartCube" 
          repo_name="FireON"  
          event_type="deploy_to_ukraina_com_ua" 
  
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.FIREON_SANITY }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
            -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"service\": \"$service\", \"version\": \"$version\", \"unit\": false, \"integration\": true}}"
