name: Trigger Target Repository Workflow

on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
     # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Deploy files with rsync
      - name: Deploy with Rsync
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr --delete
          path: .
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_key: ${{ secrets.REMOTE_KEY }}
          remote_path: ${{ secrets.REMOTE_PATH }}  

      # Step 3: Execute remote commands via SSH
      - name: Deploy Application on Remote Server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/cyclone/fireon.com.ua/admin/
            rm -rf node_modules package-lock.json
            ls
            nvm use 20
            nvm install-latest-npm
            npm install
            npm run build
      - name: Trigger Workflow in Another Repository
        run: |
          # Set the required variables
          repo_owner="MartCube" 
          repo_name="FireON"  
          event_type="deploy_to_ukraina_com_ua" 
  
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.FIREON_SANITY }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
            -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"service\": \"$service\", \"version\": \"$version\", \"unit\": false, \"integration\": true}}"
